version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8088:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - loraforge_data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  db:
    image: postgres
    environment:
      POSTGRES_DB: loraforge_db
      POSTGRES_USER: loraforge_user
      POSTGRES_PASSWORD: loraforge_password
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis
    volumes:
      - redis_data:/data

  worker:
    build:
      context: ./backend
    command: celery -A app.celery worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - loraforge_data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  loraforge_data:
  db_data:
  redis_data:
